### PR TITLE
Add bc

### PR DESCRIPTION
**Pull request by juanrunzio**
This PR adds `bc`, a command line calculator.  
Results were tested across different OS, such as Windows x86_64, Linux x86_64, macOS. 
Tests can be run with:
```sh
make -j test
```

### CODE REVIEW

**Comment by rladaga** [comment]
[Here](https://github.com/juanrunzio/superconfigure/actions/runs/8600062086) you can see that the Workflow runs perfectly, and all the jobs are completed without errors.

**Review by jart — COMMENTED** [review]
Looks good to me. @ahgamut will approve.

**Review by ahgamut — COMMENTED** [review]
:+1: `cli/BUILD.mk` is unsorted, but I'll add a commit for that

**Comment by franalbani** [comment]
@ahgamut @jart we are considering in adding `top` `htop` `btop`. Do you foresee any problem?

**Pull request merged**
